version: 2.1
jobs:
  test-unit:
    docker: 
      - image: golang:1.12.6-alpine
    steps:
      - checkout
      - run:
          name: Unit Test
          command: |
            echo 'Running Unit tests'
            apk add gcc && apk add musl-dev
            go test -mod=vendor ./test
  # test-lint-2:
  #   docker: 
  #     - image: golang:1.12.6-alpine # the primary container, where your job's commands are run
  #   steps:
  #     - checkout # check out the code in the project directory
  #     - run:
  #         name: Lint Test 2.0
  #         command: |
  #           echo 'Running Lint tests'
  #           apk add bash
  #           ./bin/golangci-lint-v1.17.1 run -c config/.golangci.yml
  test-lint:
      docker: 
        - image: golangci/golangci-lint:v1.17.1
      steps:
        - checkout 
        - run:
            name: Lint Test
            command: |
              echo 'Running Lint tests 2'
              /usr/bin/golangci-lint run -c config/.golangci.yml
  build: 
    docker:
      - image: alpine:3.10.2
    steps:
      - run: echo "Building image [Not Yet Implemented]"
  deploy: 
    docker:
      - image: alpine:3.10.2
    steps:
      - run: |
          apk add openssh
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker-compose.yaml root@206.189.38.16:/root
          ssh -o StrictHostKeyChecking=no root@206.189.38.16 "docker-compose up"

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test-unit
      - test-lint
      - build:
          requires:
            - test-unit
            - test-lint
      - deploy:
          requires:
            - build