version: 2.1
jobs:
  build1:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: printing hello
          command: echo 'hello'
  build2:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: printing hello
          command: echo 'hello'
  build3: 
    docker:
      - image: alpine:3.10.2
    steps:
      - run: echo "Deploy to AWS [Not Yet Implemented]"
                        
workflows:
  version: 2
  build_and_test: # name of your workflow
    jobs:
      - build1
      - build2
      - build3:
        requires:
           - build1